#define BUFFER_NULL             1
#define BUFFER_NOT_NULL         2
#define NONZERO_LENGTH          3
#define WRONG_CAPACITY          4
#define WRONG_GROWTH_RATE       5
#define WRONG_SIZE              6
#define WRONG_LENGTH            7
#define FUNCTION_FAILED         8
#define FUNCTION_SUCCEEDED      9
#define FUNCTION_LOGIC_FAILED   10
#define ITEM_ERROR              11
#define NOT_EQUAL               12
#define EQUAL                   13
